# coding: utf-8
import web
from config import config
from base import db, auth


if __name__ == "__main__":
    now = web.db.SQLLiteral("CURRENT_TIMESTAMP")
    user = auth.create_user(web.config.email_from,
        password="111111",
        title=u"Adminstrator",
        role="admin",
        is_active=True,
    )
    # System root folder
    db.insert("documents",
        id=1,
        level=0,
        user_id=user.id,
        title=u"Storage",
        filetype="folder",
        is_navigatable=True,
        is_published=True,
        is_system=True,
        created_at=now,
    )

    # Main page
    db.insert("pages",
        id=1,
        level=0,
        user_id=user.id,
        slug="",
        path="/",
        title="Index page",
        name="Index page",
        is_navigatable=True,
        is_published=False,
    )
    db.insert("blocks",
        id=1,
        page_id=1,
        level=0,
        user_id=user.id,
        template="page",
        is_published=True,
        created_at=now,
    )
    # Global header
    db.insert("blocks",
        id=2,
        page_id=None,
        container="global_header",
        level=0,
        user_id=user.id,
        position=1,
        template="cols_33_67",
        is_published=True,
        created_at=now,
    )
    db.insert("blocks",
        id=3,
        block_id=2,
        blocks="2",
        level=1,
        user_id=user.id,
        position=1,
        is_published=True,
        created_at=now,
        template="richtext",
        container="secondary1",
        content=u'<p><a href="/"><strong>Stonegarden</strong></a></p>',
        content_cached=u'''
            <p><a href="/"><strong>Stonegarden</strong></a></p>''',
    )
    db.insert("blocks",
        id=4,
        block_id=2,
        blocks="2",
        level=1,
        user_id=user.id,
        position=1,
        is_published=True,
        created_at=now,
        template="navigation",
        container="primary",
    )
    db.insert("blocks",
        id=5,
        page_id=None,
        container="global_footer",
        level=0,
        user_id=user.id,
        position=1,
        template="cols_67_33",
        is_published=True,
        created_at=now,
    )
    db.insert("blocks",
        id=6,
        block_id=5,
        blocks="5",
        level=1,
        user_id=user.id,
        position=1,
        is_published=True,
        created_at=now,
        template="richtext",
        container="secondary1",
        content='<p>© Site Authors</p>',
        content_cached='<p>© Site Authors</p>',
    )
    # Inner page
    db.insert("pages",
        id=2,
        level=1,
        page_id=1,
        user_id=user.id,
        pages="1",
        slug="docs",
        path="/docs",
        title=u"Documentation",
        name=u"Documentation",
        is_navigatable=True,
        is_published=False,
    )
    db.insert("blocks",
        id=7,
        page_id=2,
        level=0,
        user_id=user.id,
        template="subpage",
        is_published=True,
        created_at=now,
    )
    db.insert("blocks",
        id=8,
        block_id=7,
        blocks="7",
        level=1,
        user_id=user.id,
        position=1,
        is_published=True,
        created_at=now,
        template="breadcrumbs",
        container="primary",
    )
